CREATE TABLE rp2016.logement 
(
    COMMUNE character(5),
    ARM character(5),
    IRIS character(9),
    ACHL character(5),
    AEMM character(4),
    AEMMR character(1),
    AGEMEN8 character(2),
    ANEM character(3),
    ANEMR character(2),
    ASCEN character(1),
    BAIN character(1),
    BATI character(1),
    CATIRIS character(1),
    CATL character(1),
    CHAU character(1),
    CHFL character(1),
    CHOS character(1),
    CLIM character(1),
    CMBL character(1),
    CUIS character(1),
    DEROU character(1),
    DIPLM_15 character varying(2),
    EAU character(1),
    EGOUL character(1),
    ELEC character(1),
    EMPLM character(2),
    GARL character(1),
    HLML character(1),
    ILETUDM character(1),
    ILTM character(1),
    IMMIM character(1),
    INAIM character(1),
    INEEM character varying(2),
    INP11M character varying(2),
    INP15M character varying(2),
    INP17M character varying(2),
    INP19M character varying(2),
    INP24M character varying(2),
    INP3M character varying(2),
    INP60M character varying(2),
    INP65M character varying(2),
    INP5M character varying(2),
    INP75M character varying(2),
    INPAM character varying(2),
    INPER character varying(2),
    INPER1 character varying(2),
    INPER2 character varying(2),
    INPOM character varying(2),
    INPSM character varying(2),
    IPONDL numeric,
    IRANM character(1),
    METRODOM character(1),
    NBPI character(2),
    RECHM character(1),
    REGION character(2),
    SANI character(1),
    SANIDOM character(2),
    SEXEM character(1),
    STAT_CONJM character(1),
    STOCD character(2),
    SURF character(1),
    TACTM character(2),
    TPM character(1,
    TRANSM character(1),
    TRIRIS character(6),
    TYPC character(1),
    TYPL character(1),
    VOIT character(1),
    WC character(1)
) ;
COPY rp2016.logement FROM 'FD_LOGEMT_2016.csv' DELIMITER ';' CSV HEADER ;
